<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository
{
}
